### ISSUE TITLE
Feature Request: Option to use one prompt for all Selected Checkpoints

### ISSUE THREAD

**Issue by cdobrich** [h43lb1t0/BatchCheckpointPrompt#15]
Feature request: Ability to enter only one set of prompt text, and check an option box to reuse it on all selected Checkpoints.

**Comment by h43lb1t0** [comment]
i am not sure what the difference is to the x/y/z plot with only one axis. Can you explain in more detail what you mean?

**Comment by cdobrich** [comment]
There are times when I want to run the same single prompt over dozens of Checkpoint files. So it would be nice to have an option to do basically this. 

![Screenshot_20230517_135550](https://github.com/h43lb1t0/BatchCheckpointPrompt/assets/3452788/7cf5b224-b308-48a6-9aea-b987211884d5)

Currently I have to count how many checkpoints I am using, then paste the '{prompt};' text the same number of times.

It would be nice if I could check an option to say "Use the {prompt} for all checkpoints" or something like that.

**Comment by h43lb1t0** [comment]
![Screenshot from 2023-05-20 22-20-49](https://github.com/h43lb1t0/BatchCheckpointPrompt/assets/65122811/04fe2d39-b491-468d-9267-90e194cc0695)
this is exactly what can be achieved with the built-in x/y/z plot. I see no reason to integrate that into this project.
