### ISSUE TITLE
Error reading checkpoint file names with square brackets []

### ISSUE THREAD

**Issue by cdobrich** [h43lb1t0/BatchCheckpointPrompt#38]
I noticed that if I have a checkpoint that has square brackets ‘[]’ in it, the batch processing script will throw an error. Is it possible to fix this?  For example: 

This name throws an error message, 

```hyper_beasts_1.2k_xl-lr1e-6-10ks-[hyperbeasts]-fp16-v3.ckpt```

but this other name works:

```hyper_beasts_1.2k_xl-lr1e-6-10ks-fp16-v3.ckpt```

**Comment by h43lb1t0** [comment]
i think i know why this happens. I'll fix it when i have time
