### ISSUE TITLE
[Bug]: RuntimeError: amount of prompts don't match with amount of checkpoints

### ISSUE THREAD

**Issue by RandyHaylor** [h43lb1t0/BatchCheckpointPrompt#42]
### Please search to see if an issue already exists for the bug you encountered, and that it hasn't been fixed in a recent build/commit.

- [X] I have searched the existing issues

### What happened?

RuntimeError: amount of prompts don't match with amount of checkpoints

I get this error no matter what I do. The instructions are pretty clear, and I've tried many different ways to set it up:
 - matching prompt number to model: i.e.:    model1,model2      prompt1;prompt2
 - ensure last comma or semicolon are left off
 - tried putting prompts in main field
 - ensured plugins like adetailer, unprompted were off so they didn't confuse the script
 - generally used default settings and tried to make it as simple as possible

### Which WebUI

AUTOMATIC1111 (Default)

### WebUI version

1.3.*

### What browsers are you seeing the problem on?

Chrome

### What Python version are you running on?

Python 3.10.x

### Steps to reproduce the problem

add plugin, select script, add names of 2 checkpoints, add two prompts, hit generate

### List of extensions

SD-CN-Animation | https://github.com/volotat/SD-CN-Animation.git | main | 2e257bbf | Tue May 30 16:49:03 2023 | unknown
SD-WebUI-BatchCheckpointPrompt | https://github.com/h43lb1t0/SD-WebUI-BatchCheckpointPrompt | main | 1856c58b | Sat Jul 8 16:29:29 2023 | unknown
SDAtom-WebUi-client-queue-ext | https://github.com/Kryptortio/SDAtom-WebUi-client-queue-ext.git | master | 9cf161b2 | Thu Jun 1 17:41:46 2023 | unknown
Stable-Diffusion-Webui-Civitai-Helper | https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper.git | main | 920ca326 | Tue May 23 11:53:22 2023 | unknown
a1111-sd-webui-lycoris | https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris | main | 025dea96 | Wed Jun 14 13:56:41 2023 | unknown
adetailer | https://github.com/Bing-su/adetailer.git | main | 57106db2 | Tue Jul 4 07:18:12 2023 | unknown
deforum | https://github.com/deforum-art/sd-webui-deforum | automatic1111-webui | 780e8a3b | Sat Jun 3 14:02:11 2023 | unknown
gif2gif | https://github.com/LonicaMewinsky/gif2gif.git | main | 5121851e | Sat May 13 14:56:04 2023 | unknown
sd-dynamic-thresholding | https://github.com/mcmonkeyprojects/sd-dynamic-thresholding | master | c8197531 | Sat Jul 1 04:22:51 2023 | unknown
sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet.git | main | 2785cbe6 | Sun Jul 2 05:20:52 2023 | unknown
sd_civitai_extension | https://github.com/civitai/sd_civitai_extension.git | main | 2dfc03c1 | Sun Jun 18 21:51:08 2023 | unknown
sd_dreambooth_extension | https://github.com/d8ahazard/sd_dreambooth_extension.git | main | dc413a14 | Tue Jun 6 04:21:36 2023 | unknown
stable-diffusion-webui-dataset-tag-editor | https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor.git | main | 7a2f4c53 | Mon Jun 5 10:12:00 2023 | unknown
stable-diffusion-webui-wd14-tagger | https://github.com/toriato/stable-diffusion-webui-wd14-tagger.git | master | 3ba3a735 | Sat Mar 25 20:32:37 2023 | unknown
unprompted | https://github.com/ThereforeGames/unprompted.git | main | f5a0cdf5 | Mon Jul 3 20:59:08 2023 | unknown
LDSR | built-in | None |   | Sun Jul 9 16:28:16 2023 |  
Lora | built-in | None |   | Sun Jul 9 16:28:16 2023 |  
ScuNET | built-in | None |   | Sun Jul 9 16:28:16 2023 |  
SwinIR | built-in | None |   | Sun Jul 9 16:28:16 2023 |  
prompt-bracket-checker | built-in | None |   | Sun Jul 9 16:28:16 2023

<br class="Apple-interchange-newline">SD-CN-Animation	https://github.com/volotat/SD-CN-Animation.git	main	[2e257bbf](https://github.com/volotat/SD-CN-Animation/commit/2e257bbfc3b76fb1323f7b22f820981c1b9f56b2)	Tue May 30 16:49:03 2023	unknown
SD-WebUI-BatchCheckpointPrompt	https://github.com/h43lb1t0/SD-WebUI-BatchCheckpointPrompt	main	[1856c58b](https://github.com/h43lb1t0/SD-WebUI-BatchCheckpointPrompt/commit/1856c58bc3d48e47bc50c0c19bbb93c4255b847c)	Sat Jul 8 16:29:29 2023	unknown
SDAtom-WebUi-client-queue-ext	https://github.com/Kryptortio/SDAtom-WebUi-client-queue-ext.git	master	[9cf161b2](https://github.com/Kryptortio/SDAtom-WebUi-client-queue-ext/commit/9cf161b22edb81f40b86fd1ee9cf929f02e032c2)	Thu Jun 1 17:41:46 2023	unknown
Stable-Diffusion-Webui-Civitai-Helper	https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper.git	main	[920ca326](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/commit/920ca3267f789a72e3225c99f069bf0be0db795d)	Tue May 23 11:53:22 2023	unknown
a1111-sd-webui-lycoris	https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris	main	[025dea96](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/commit/025dea96720197dd4486a5bb8e2f4d72a95a3088)	Wed Jun 14 13:56:41 2023	unknown
adetailer	https://github.com/Bing-su/adetailer.git	main	[57106db2](https://github.com/Bing-su/adetailer/commit/57106db2b1146d82d981d951254d21a71076ab86)	Tue Jul 4 07:18:12 2023	unknown
deforum	https://github.com/deforum-art/sd-webui-deforum	automatic1111-webui	[780e8a3b](https://github.com/deforum-art/sd-webui-deforum/commit/780e8a3bf4385fe121b897826206476c0f16ef61)	Sat Jun 3 14:02:11 2023	unknown
gif2gif	https://github.com/LonicaMewinsky/gif2gif.git	main	[5121851e](https://github.com/LonicaMewinsky/gif2gif/commit/5121851e3941c420253f3a20a0f8e49bed86f0bb)	Sat May 13 14:56:04 2023	unknown
sd-dynamic-thresholding	https://github.com/mcmonkeyprojects/sd-dynamic-thresholding	master	[c8197531](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/commit/c81975313514560ab0aa123671ea466dfcde2d41)	Sat Jul 1 04:22:51 2023	unknown
sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet.git	main	[2785cbe6](https://github.com/Mikubill/sd-webui-controlnet/commit/2785cbe61a61c137d4e980752771f6329b03612a)	Sun Jul 2 05:20:52 2023	unknown
sd_civitai_extension	https://github.com/civitai/sd_civitai_extension.git	main	[2dfc03c1](https://github.com/civitai/sd_civitai_extension/commit/2dfc03c17304278ca0b456366cc7871a2af8377b)	Sun Jun 18 21:51:08 2023	unknown
sd_dreambooth_extension	https://github.com/d8ahazard/sd_dreambooth_extension.git	main	[dc413a14](https://github.com/d8ahazard/sd_dreambooth_extension/commit/dc413a14379b165355502d9f65856c40a4bb5b6f)	Tue Jun 6 04:21:36 2023	unknown
stable-diffusion-webui-dataset-tag-editor	https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor.git	main	[7a2f4c53](https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor/commit/7a2f4c53fbce62b2bda3b220381985b75fdd6390)	Mon Jun 5 10:12:00 2023	unknown
stable-diffusion-webui-wd14-tagger	https://github.com/toriato/stable-diffusion-webui-wd14-tagger.git	master	[3ba3a735](https://github.com/toriato/stable-diffusion-webui-wd14-tagger/commit/3ba3a7356447e91c15ffb6d01ca61f878a2292a8)	Sat Mar 25 20:32:37 2023	unknown
unprompted	https://github.com/ThereforeGames/unprompted.git	main	[f5a0cdf5](https://github.com/ThereforeGames/unprompted/commit/f5a0cdf56a5e8e0895fecde35942a69ffb6a1767)	Mon Jul 3 20:59:08 2023	unknown
LDSR	[built-in](http://127.0.0.1:7860/)	None		Sun Jul 9 16:28:16 2023	
Lora	[built-in](http://127.0.0.1:7860/)	None		Sun Jul 9 16:28:16 2023	
ScuNET	[built-in](http://127.0.0.1:7860/)	None		Sun Jul 9 16:28:16 2023	
SwinIR	[built-in](http://127.0.0.1:7860/)	None		Sun Jul 9 16:28:16 2023	
prompt-bracket-checker	[built-in](http://127.0.0.1:7860/)	None		Sun Jul 9 16:28:16 2023

**Comment by h43lb1t0** [comment]
have you separated the prompts with ";" and and not ","? and the other way around for the checkpoints?
could you share a screenshot?

**Comment by RandyHaylor** [comment]
I really appreciate the response!  I was getting some long loading times so I spent an hour in dependency hell to set up the right a1111 dependencies in the venv before returning to this...

Turns out a model name I was using had spaces in the name and that was breaking it. I renamed the file and it worked!!

What an awesome script!  This is exactly what I was looking for for testing.  I'm shocked that more people haven't set up things like this.

**Comment by RandyHaylor** [comment]
Hope you don't mind me asking - does this work with adetailer?  Are there ways to get more of the features in the prompts (like coding them into the prompt)?  

Also, is there a way to just have it repeat one prompt without needing to paste it each time per model?

**Comment by h43lb1t0** [comment]
all available  syntax is documented in the scripts help tab. I've just started learning adetailer today, haven't tested it yet. For just one prompt use x/y/z plot with checkpoints name as axis option.

**Comment by RandyHaylor** [comment]
Thanks!!
