### ISSUE TITLE
[Feature Request]: Ability to use styles

### ISSUE THREAD

**Issue by drphero** [h43lb1t0/BatchCheckpointPrompt#50]
### Please search to see if an issue already exists for the feature you want, and that it hasn't been fixed in a recent build/commit.

- [X] I have searched the existing issues

### What would this feature do?

This feature would allow users to select preexisting styles, including negative prompts, in order to avoid copy pasting mass amounts of prompts and manually fixing the negative prompt syntax.

### What is the workflow for your feature idea?

It could work similar to how it does for x/y/z plot, where the user is shown a list of styles to select.

**Comment by h43lb1t0** [comment]
I'll add this to my TODO list and will checkout if it fits in for me

**Comment by h43lb1t0** [comment]
@drphero what is your idea for saving the checkpoints this way? I understand your idea like replacing/adding to the saved values dropdown the option to select styles. But not only styles, but also checkpoints are needed.

**Comment by drphero** [comment]
~~I was thinking it could be an optional separate box below the prompt templates box that would be combined with the prompts box when saved. Since multiple styles could be used for a single generation, it would need to allow that.
So maybe it would look something like this:~~

~~**Checkpoint Names**~~
~~darkSushi25D25D_v40.safetensors @index:17,~~

~~**Prompts/prompt templates for Checkpoints**~~
~~{prompt} @index:17;~~

~~**Styles for Checkpoints**~~
~~style1, style2 @index:17;~~

~~Of course the style names would need to match ones that the user already has saved. It would be good if there was a way to easily add in the style names without having to type them all, but I'm not sure how that would work.~~

**Comment by drphero** [comment]
@h43lb1t0 I just thought of a better way. So it's like the way you implemented negative prompts. Styles could be used like {{style: stylename}}. But since styles can include negative prompts themselves, this would need to take that into account.

**Comment by h43lb1t0** [comment]
@drphero I think I like this way. That should'nd be to hard to implement.

**Comment by h43lb1t0** [comment]
@drphero i've added it. Could you try it before i merge it? I don't use styles that much and can't realy say if the implementation is good or not.

**Comment by drphero** [comment]
@h43lb1t0 I've given it a try now. The only problem I've found so far is that it stacks the styles. So if you have something like three checkpoints and three matching prompt templates, each with a different style, the first one comes out correct, but then the 2nd one will use its own, but also the 1st style added. And the 3rd will have its own, but the 2nd and 1st style also added.

**Comment by drphero** [comment]
@h43lb1t0 By changing line 214 in batchCheckpointsPrompt.py from `p.styles.extend(batch_params.style)` to `p.styles = (batch_params.style)` seems to fix this.

Is it possible to use multiple styles for one checkpoint? I can't figure out what the formatting would be.

- {{style:styleone}} {{style:styletwo}}
- {{style:styleone,styletwo}}
- etc

**Comment by h43lb1t0** [comment]
@drphero jmade some changes. Now it is possible to use multiple styles. Just list them one after another. The last style is the one the base prompt will be inserted to.

**Comment by drphero** [comment]
@h43lb1t0 Everything seems to be working as far as I can tell. Great work!
