### ISSUE TITLE
[Bug]: Grids is not saved in folders specified under settings in the webui.

### ISSUE THREAD

**Issue by Qwindrix** [h43lb1t0/BatchCheckpointPrompt#57]
### Please search to see if an issue already exists for the bug you encountered, and that it hasn't been fixed in a recent build/commit.

- [X] I have searched the existing issues

### What happened?

Hi

Not sure if this is a bug or a missing feature but the generated grids are not saved in the folders specified in Settings - Path for saving - Output directory for grids; if empty, defaults to two directories below (or Output directory for txt2img grids).
The grid still defaults to <webui dir>/Outputs/txt2img-grids/Checkpoint-Prompt-Loop/

(btw, I'm using webui ver 1.7.0 but it's not listed in the dropdown below)

### Which WebUI

AUTOMATIC1111 (Default)

### WebUI version

1.5.*

### What browsers are you seeing the problem on?

Firefox

### What Python version are you running on?

Python 3.10.x

### Steps to reproduce the problem

Generate a grid in txt2img..

### List of extensions

no

**Comment by h43lb1t0** [comment]
Currectly it saves at the stanndart path. I'm not checking the settings. I'll implement this.

**Comment by h43lb1t0** [comment]
Hey, could you try the branch `path`? I think it should work like you want now. open cmd/terminal in the extentions folder
1. `git fetch`
2. `git checkout path`
3. `git pull`

**Comment by Qwindrix** [comment]
Hi

I just did a quick check and the grid now saves in the custom folder.
Also, I did not see any error or anything in the debug info that was generated while ran the script.
So it seems to be ok now.

Thank you for this update.

**Comment by h43lb1t0** [comment]
perfect. I forgot to set debug to False again. Thanks.
