### ISSUE TITLE
[Bug]: Extension changes orientation when generate

### ISSUE THREAD

**Issue by Bozek80** [h43lb1t0/BatchCheckpointPrompt#62]
### Please search to see if an issue already exists for the bug you encountered, and that it hasn't been fixed in a recent build/commit.

- [X] I have searched the existing issues

### What happened?

When I try to create a portrait photo, the extension turns it into a landscape, and vice versa. I only make a portrait if I invert the dimensions.

I use AUTOMATIC1111 1.8.0 version. It worked with version 1.7.0.

![image](https://github.com/h43lb1t0/SD-WebUI-BatchCheckpointPrompt/assets/127804662/14c3250c-093f-43f5-8aa1-ec4049bbf21b)

![image](https://github.com/h43lb1t0/SD-WebUI-BatchCheckpointPrompt/assets/127804662/7eaadf3b-cc39-4201-a7ba-84d9f74b613f)

### Which WebUI

AUTOMATIC1111 (Default)

### WebUI version

other

### What browsers are you seeing the problem on?

Chrome

### What Python version are you running on?

Python 3.10.x

### Steps to reproduce the problem

1. Set dimensions to portrait.
2. Use the extension.
3. Hit Generate

### List of extensions

No

**Comment by h43lb1t0** [comment]
just a simple typo. It's fixed with #63 . I don't know how i did not catch that while Testing..
